# Generated by Django 4.2.10 on 2024-06-18 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookRadar', '0006_alter_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BookRadar.book'),
        ),
    ]
